version: "3"
services:
  app:
    build: .
    ports:
      - 3000:3000
    env_file:
      - docker.env
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6-alpine
    ports:
      - "5433:5433"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      - PGPORT=5433

volumes:
  database-data: {}
